package me.golemcore.plugins.golemcore.brain;

import org.springframework.beans.factory.annotation.Autowired;
import me.golemcore.plugin.api.extension.spi.PluginActionResult;
import me.golemcore.plugin.api.extension.spi.PluginSettingsCatalogItem;
import me.golemcore.plugin.api.extension.spi.PluginSettingsContributor;
import me.golemcore.plugin.api.extension.spi.PluginSettingsField;
import me.golemcore.plugin.api.extension.spi.PluginSettingsSection;
import org.springframework.stereotype.Component;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Component
public class BrainPluginSettingsContributor implements PluginSettingsContributor {

    private static final String SECTION_KEY = "main";

    private final BrainPluginConfigService configService;

    @Autowired
    public BrainPluginSettingsContributor(BrainPluginConfigService configService) {
        this.configService = configService;
    }

    @Override
    public String getPluginId() {
        return BrainPluginConfigService.PLUGIN_ID;
    }

    @Override
    public List<PluginSettingsCatalogItem> getCatalogItems() {
        return List.of(PluginSettingsCatalogItem.builder()
                .pluginId(BrainPluginConfigService.PLUGIN_ID)
                .pluginName("brain")
                .provider("golemcore")
                .sectionKey(SECTION_KEY)
                .title("GolemCore Brain")
                .description("GolemCore Brain API credentials and wiki tool behavior.")
                .blockKey("tools")
                .blockTitle("Tools")
                .blockDescription("Tool-specific runtime behavior and integrations")
                .order(62)
                .build());
    }

    @Override
    public PluginSettingsSection getSection(String sectionKey) {
        requireSection(sectionKey);
        BrainPluginConfig config = configService.getConfig();
        Map<String, Object> values = new LinkedHashMap<>();
        values.put("enabled", Boolean.TRUE.equals(config.getEnabled()));
        values.put("baseUrl", config.getBaseUrl());
        values.put("apiToken", "");
        values.put("defaultSpaceSlug", config.getDefaultSpaceSlug());
        values.put("dynamicApiSlug", config.getDynamicApiSlug());
        values.put("defaultIntellisearchLimit", config.getDefaultIntellisearchLimit());
        values.put("allowWrite", Boolean.TRUE.equals(config.getAllowWrite()));
        return PluginSettingsSection.builder()
                .title("GolemCore Brain")
                .description("Configure the Brain wiki API tool and optional dynamic relevance endpoint.")
                .fields(List.of(
                        PluginSettingsField.builder()
                                .key("enabled")
                                .type("boolean")
                                .label("Enable Brain tool")
                                .description("Allow the model to use the GolemCore Brain wiki tool.")
                                .build(),
                        PluginSettingsField.builder()
                                .key("baseUrl")
                                .type("text")
                                .label("Brain Base URL")
                                .description(
                                        "Base URL of the GolemCore Brain instance, for example https://brain.example.")
                                .placeholder("https://brain.example")
                                .build(),
                        PluginSettingsField.builder()
                                .key("apiToken")
                                .type("secret")
                                .label("Brain API Token")
                                .description("Optional bearer token generated by Brain API key settings.")
                                .placeholder("Enter API token")
                                .build(),
                        PluginSettingsField.builder()
                                .key("defaultSpaceSlug")
                                .type("text")
                                .label("Default Space Slug")
                                .description("Brain space used when the tool call does not provide space_slug.")
                                .placeholder("default")
                                .build(),
                        PluginSettingsField.builder()
                                .key("dynamicApiSlug")
                                .type("text")
                                .label("Dynamic Relevance Endpoint")
                                .description("Optional Brain dynamic API slug used by intellisearch.")
                                .placeholder("brain-relevance")
                                .build(),
                        PluginSettingsField.builder()
                                .key("defaultIntellisearchLimit")
                                .type("number")
                                .label("Default Intellisearch Limit")
                                .description("Maximum fallback pages to fetch when dynamic endpoint is not configured.")
                                .min(1.0)
                                .max(20.0)
                                .step(1.0)
                                .build(),
                        PluginSettingsField.builder()
                                .key("allowWrite")
                                .type("boolean")
                                .label("Allow Write Operations")
                                .description("Allow create, update, delete, ensure, move, and copy operations.")
                                .build()))
                .values(values)
                .build();
    }

    @Override
    public PluginSettingsSection saveSection(String sectionKey, Map<String, Object> values) {
        requireSection(sectionKey);
        BrainPluginConfig config = configService.getConfig();
        config.setEnabled(readBoolean(values, "enabled", false));
        config.setBaseUrl(readString(values, "baseUrl", config.getBaseUrl()));
        String apiToken = readString(values, "apiToken", null);
        if (apiToken != null && !apiToken.isBlank()) {
            config.setApiToken(apiToken);
        }
        config.setDefaultSpaceSlug(readString(values, "defaultSpaceSlug", config.getDefaultSpaceSlug()));
        config.setDynamicApiSlug(readString(values, "dynamicApiSlug", config.getDynamicApiSlug()));
        config.setDefaultIntellisearchLimit(readInteger(values, "defaultIntellisearchLimit",
                config.getDefaultIntellisearchLimit()));
        config.setAllowWrite(readBoolean(values, "allowWrite", false));
        configService.save(config);
        return getSection(sectionKey);
    }

    @Override
    public PluginActionResult executeAction(String sectionKey, String actionId, Map<String, Object> payload) {
        requireSection(sectionKey);
        throw new IllegalArgumentException("Unknown Brain action: " + actionId);
    }

    private void requireSection(String sectionKey) {
        if (!SECTION_KEY.equals(sectionKey)) {
            throw new IllegalArgumentException("Unknown Brain settings section: " + sectionKey);
        }
    }

    private boolean readBoolean(Map<String, Object> values, String key, boolean defaultValue) {
        Object value = values.get(key);
        return value instanceof Boolean bool ? bool : defaultValue;
    }

    private int readInteger(Map<String, Object> values, String key, int defaultValue) {
        Object value = values.get(key);
        if (value instanceof Number number) {
            return number.intValue();
        }
        if (value instanceof String text && !text.isBlank()) {
            try {
                return Integer.parseInt(text);
            } catch (NumberFormatException ignored) {
                return defaultValue;
            }
        }
        return defaultValue;
    }

    private String readString(Map<String, Object> values, String key, String defaultValue) {
        Object value = values.get(key);
        if (value instanceof String text) {
            return text;
        }
        return defaultValue;
    }
}
